version: '3.8'
services:
  app:
    platform: linux/x86_64
    build: .
    image: app:latest
    ports:
      - "8080:8080"
    depends_on:
      - mysql
  mysql:
    platform: linux/x86_64
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: cafe-api-db
      MYSQL_DATABASE: cafe-api-db
      MYSQL_USER: cafe-api-db
      MYSQL_PASSWORD: cafe-api-db
    ports:
      - "3306:3306"