version: '3.8'
services:
  app:
    platform: linux/x86_64
    build: .
    image: cafe-api-task:latest
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/cafe-api-db?serverTimezone=Asia/Seoul
      SPRING_DATASOURCE_USERNAME: cafe-api-db
      SPRING_DATASOURCE_PASSWORD: cafe-api-db
  mysql:
    platform: linux/x86_64
    image: mysql:5.7
    hostname: mysql
    environment:
      MYSQL_ROOT_PASSWORD: cafe-api-db
      MYSQL_DATABASE: cafe-api-db
      MYSQL_USER: cafe-api-db
      MYSQL_PASSWORD: cafe-api-db
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-init:/docker-entrypoint-initdb.d
      - ./mysql-init/my.cnf:/etc/mysql/conf.d/my.cnf:ro
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
networks:
  default:
    name: cafe-api-network
  external:
    name: cafe-api-network