version: '3.8'
services:
  app:
    platform: linux/x86_64
    build: .
    image: cafe-api-task:latest
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/cafe-api-db?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
      SPRING_DATASOURCE_USERNAME: cafe-api-db
      SPRING_DATASOURCE_PASSWORD: cafe-api-db
  mysql:
    platform: linux/x86_64
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: cafe-api-db
      MYSQL_DATABASE: cafe-api-db
      MYSQL_USER: cafe-api-db
      MYSQL_PASSWORD: cafe-api-db
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-init:/docker-entrypoint-initdb.d
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci

