spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cafe-api-db?useSSL=false&serverTimezone=Asia/Seoul
    username: cafe-api-db
    password: cafe-api-db
  jpa:
    show-sql: true
    properties:
      defer-datasource-initialization: true
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: update

