spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/cafe-api-db?useSSL=false&serverTimezone=Asia/Seoul
    username: cafe-api-db
    password: cafe-api-db
  jpa:
    show-sql: true
    properties:
      defer-datasource-initialization: true
      hibernate:
        format_sql: true
        highlight_sql: true
        hbm2ddl:
          auto: update
          naming:
            physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl # 카멜케이스를 언더스코어로 변경



jwt:
  secret-key: in_a_hole_in_the_ground_there_lived_a_hobbit # 땅 속 어느 굴에 한 호빗이 살고 있었다.
  expire-length: 86400000 # 1 day


