### 사장님 로그인 API
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "phoneNumber": "01012340001",
  "password": "password1234"
}
> {%
    client.global.set("token", response.headers.valuesOf("Authorization")[0]);
%}


### 상품 등록 API
< {%
    request.variables.set("token", client.global.get("token"));
%}
POST http://localhost:8080/api/product/manage
Content-Type: application/json
Authorization: {{token}}

{
  "category": "중식",
  "price": 7000,
  "cost": 2000,
  "name": "차돌짬뽕",
  "description": "매콤하고 고기 많은 차돌짬뽕",
  "barcode": "I1234567890",
  "expirationDate": "2024-02-19",
  "size": "SMALL"
}
> {%
    client.global.set("product_id", response.body.data.id);
%}


### 상품 정보 수정 API
< {%
    request.variables.set("token", client.global.get("token"));
    request.variables.set("product_id", client.global.get("product_id"));
%}
PATCH http://localhost:8080/api/product/manage/{{product_id}}
Content-Type: application/json
Authorization: {{token}}

{
  "category": "중식",
  "price": 9000,
  "cost": 2000,
  "name": "차돌짬뽕",
  "description": "매콤하고 고기 많은 차돌짬뽕",
  "barcode": "I1234567890",
  "expirationDate": "2024-02-19",
  "size": "SMALL"
}


### 상품 삭제 API
< {%
    request.variables.set("token", client.global.get("token"));
    request.variables.set("product_id", client.global.get("product_id"));
%}
DELETE http://localhost:8080/api/product/manage/{{product_id}}
Content-Type: application/json
Authorization: {{token}}


### 상품 목록 조회 API
< {%
    request.variables.set("product_id", client.global.get("product_id"));
%}
GET http://localhost:8080/api/product/query
Authorization: {{token}}


### 상품 상세 조회 API
< {%
    request.variables.set("token", client.global.get("token"));
    request.variables.set("product_id", client.global.get("product_id"));
%}
GET http://localhost:8080/api/product/query/{{product_id}}
Content-Type: application/json
Authorization: {{token}}


### 상품 검색 API
< {%
    request.variables.set("token", client.global.get("token"));
%}
GET http://localhost:8080/api/product/query/search?name=차돌짬뽕
Content-Type: application/json
Authorization: {{token}}


### 상품 검색 API (초성검색)
< {%
    request.variables.set("token", client.global.get("token"));
%}
GET http://localhost:8080/api/product/query/search?name=ㅊㄷㅉㅃ
Content-Type: application/json
Authorization: {{token}}